services:
  ubuntu_x86:
    image: rokodev/compiler-gcc-${COMPILER_V}-img:1.0
    container_name: build-test-host
    platform: linux/amd64
    tty: true
    environment:
      - SOURCE_DIR=${SOURCE_DIR}
      - BUILD_DIR=${BUILD_DIR}
      - CC=${CC}
      - CXX=${CXX}
      - RANLIB=${RANLIB}
    volumes:
      - type: bind
        source: ${BUILD_DIR}
        target: ${BUILD_DIR}
      - type: bind
        read_only: true
        source: ${SOURCE_DIR}
        target: ${SOURCE_DIR}