FROM rokodev/ubuntu2004-dev@sha256:106629a0ef28ff0e7b3faa3f79bf8e1bcf2aa8e2c8330bf2f2ce7b6179f167a2

RUN apt-get install -y build-essential

LABEL description="Adds build-essential tools(gcc 9.4.0)"

WORKDIR /home/projects